import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { routing } from '@/lib/i18n/routing';
import { hasLocale, Locale, NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import { ReactNode } from 'react';

import { AuthInitializer } from '@/features/auth/components/auth-initializer';
import { QueryProvider } from '@/providers/query-provider';

import './globals.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

type Props = {
	children: ReactNode;
	params: Promise<{ locale: Locale }>;
};

export default async function RootLayout({ children, params }: Props) {
	const { locale } = await params;
	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	return (
		<html lang={locale}>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<main className='bg-accent-foreground min-h-screen flex items-center justify-center'>
					<QueryProvider>
						<AuthInitializer />
						<NextIntlClientProvider>{children}</NextIntlClientProvider>
					</QueryProvider>
				</main>
			</body>
		</html>
	);
}
